### ISSUE TITLE
Cannot build with Eclipse 2019-03

### ISSUE THREAD

**Issue by CaptainSaveACode** [philjord/ElderScrollsExplorer#1]
I am unable to build from source following the directions in 
[README.md](https://github.com/philjord/ElderScrollsExplorer/blob/master/README.md#to-build-the-code) with a new install of Eclipse and OpenJDK.

Using:
Eclipse IDE for Java Developers 2019-03
OpenJDK 8 LTS

After reaching the error about java3d-core and importing it manually, java3d-core can't find the `org.jogamp.vecmath` package.

Would you know if this is an issue with Eclipse or one of the projects?

**Comment by philjord** [comment]
It's probably something to do with the psf file import. I suspect that the vecmath project also didn't get imported. It may just need the same right click import project on the vecmath project in your git repository list.

I've attached a screen shot of what my workspace looks like with all the projects imported and built.
(you can ignore the hkxpack project)

![image](https://user-images.githubusercontent.com/4186290/59380908-4dc39500-8dae-11e9-89c0-b20528237c66.png)

**Comment by CaptainSaveACode** [comment]
I was able to get the project to compile & run by editing the build path for the vecmath project. Maven install was reporting that it was compiling an empty jar until I changed the src directory in the Build Path options.

My next issue is that I'm getting a `java.lang.VerifyError` after I select a game to load. I've tried Fallout 3, NV, and 4 and they all throw this error.
```
Exception in thread "Set current Cell form id = 60" java.lang.VerifyError: Stack map does not match the one at exception handler 319
....
Stackmap Table:
    full_frame(@319,{Top,Object[#201],Object[#218],Float,Integer,Object[#94]},{Object[#220]})

	at nifbullet.cha.NBControlledChar.<init>(NBControlledChar.java:51)
	at scrollsexplorer.simpleclient.physics.PhysicsDynamics.<init>(PhysicsDynamics.java:93)
	at scrollsexplorer.simpleclient.physics.PhysicsSystem.cellChanged(PhysicsSystem.java:126)
	at scrollsexplorer.simpleclient.BethWorldPhysicalBranch.<init>(BethWorldPhysicalBranch.java:92)
	at scrollsexplorer.simpleclient.SimpleBethCellManager$1.run(SimpleBethCellManager.java:297)
```

Searching around Google/StackOverflow suggests it may be an ASM problem. I saw the comments in the `build.xml` file for jbullet1.1 to use the Alternate JRE but it didn't seem to fix it (maybe I didn't do it right?)
```
<!-- make sure you build the project first-->
<!-- NOTE!!!!!!!!!!!! do not use workspace default JRE is includes a bad asm jar, over this one-->
<!-- Both project and ant build must use Alternate JRE and pick it from list-->
```

Thanks a lot for your help, it seems like a nice project!

**Comment by philjord** [comment]
Hi there!
Thanks for taking a look at my code, sorry my hobby code is such a mess, I'm working on Mavenizing as much as I can of it.
If I can ever get JBullet1.1 up to maven central then this issue might not have happened for you.

I've never had this particular error message pop up, but I agree the GoogleNet strongly suggests it's the ASM gone wrong, and by the look of it, the Transform tr = NifBulletUtil.createTrans(baseTrans); line in the constructor of the NBControllerChar may well be the first time the JBullet1.1 project code is called in the runtime.
I suggest you try taking the JBullet1.1 project out of the BuildPath of ElderScrollsExplorerBase and ElderScrollsExplorer and instead "add external jar" and point to the /dist/ jbullet1.1.jar file in the 

jbullet1.1. project
(or here https://github.com/philjord/jbullet1.1/blob/master/jbullet1.1/dist/jbullet1.1.jar )
And see if that changes the message.
Thanks again,
Phil.
